port: 8081
datasource: "postgres"
node_info_interval: 30
api_prefix: /api/v1

jwt:
  expiration: 3600
  public_key_file:

postgres:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "123456"
  db_name: "blank_web_app"
  sslmode: "require"
  max_open_conns: 10
  max_idle_conns: 2


iam:
  host: "localhost"
  port: 8080

log:
  log_level: info

rabbitmq:
  host: "127.0.0.1"
  port: 5672
  username: "guest"
  password: "guest"
  topic: "k8s_topic"

prometheus:
  serverUrl: "localhost:9090"

mailServer:
  smtpHost: "smtp.qq.com"
  smtpPort: 587
  userName: "i.guochen@qq.com"
  password: "ysfadpsswlcldcjh"
  status: true

redis:
  host: 127.0.0.1:6379
  auth: ""
  db: 0
